import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:mafia_master/engine/information/confrontation_generator.dart';
import 'package:mafia_master/engine/information/game_history.dart';
import 'package:mafia_master/engine/information/records.dart';
import 'package:mafia_master/engine/information/trace_generator.dart';
import 'package:mafia_master/engine/models/enums.dart';
import 'package:mafia_master/engine/models/information_enums.dart';
import 'package:mafia_master/engine/models/match_settings.dart';
import 'package:mafia_master/engine/models/player.dart';

/// The Dart half of the golden-vector contract (doc 10 §5.1).
///
/// `supabase/tests/golden_vectors.json` is generated by
/// `tool/golden_vectors.dart` and read by two tests: this one, and
/// `supabase/tests/golden_vectors.test.ts`. Neither implementation can pass by
/// agreeing with itself — they agree with the same file or the build fails.
///
/// What this side is really guarding is *drift on purpose*: a change to the
/// Dart generator will fail here, which is the reminder that the TypeScript
/// port has to change with it and the vectors regenerated in the same commit.
void main() {
  late Map<String, dynamic> vectors;

  setUpAll(() {
    final file = File('supabase/tests/golden_vectors.json');
    expect(file.existsSync(), isTrue,
        reason: 'run `dart run tool/golden_vectors.dart`');
    vectors = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  });

  NightRecord decodeNight(Map<String, dynamic> json) => NightRecord(
        nightNumber: json['nightNumber'] as int,
        suspicions: {
          for (final e in (json['suspicions'] as Map).entries)
            int.parse(e.key as String): e.value as int?,
        },
        reasons: const {},
        victim: json['victim'] as int?,
        saveOccurred: json['saveOccurred'] as bool,
        savedSeat: json['savedSeat'] as int?,
        revealedTrace: json['revealedTrace'] == null
            ? null
            : TraceType.values
                .firstWhere((t) => t.name == json['revealedTrace']),
        resolved: json['resolved'] as bool,
      );

  Confrontation decodeConfrontation(Map<String, dynamic> json) => Confrontation(
        type: ConfrontationType.values
            .firstWhere((t) => t.name == json['type']),
        targetSeat: json['targetSeat'] as int,
        evidenceSeat: json['evidenceSeat'] as int?,
        evidenceSeat2: json['evidenceSeat2'] as int?,
        evidenceDay: json['evidenceDay'] as int?,
        count: json['count'] as int?,
      );

  DayRecord decodeDay(Map<String, dynamic> json) => DayRecord(
        dayNumber: json['dayNumber'] as int,
        openingAccusations: {
          for (final e in (json['openingAccusations'] as Map).entries)
            int.parse(e.key as String): e.value as int,
        },
        confrontation: json['confrontation'] == null
            ? null
            : decodeConfrontation(
                json['confrontation'] as Map<String, dynamic>),
        votes: {
          for (final e in (json['votes'] as Map).entries)
            int.parse(e.key as String): e.value as int?,
        },
        speakingSeconds: {
          for (final e in (json['speakingSeconds'] as Map).entries)
            int.parse(e.key as String): e.value as int,
        },
        whispers: [
          for (final w in (json['whispers'] as List))
            WhisperMeta(
              id: WhisperMeta.idFor(
                day: (w as Map)['day'] as int,
                fromSeat: w['fromSeat'] as int,
                toSeat: w['toSeat'] as int,
              ),
              day: w['day'] as int,
              fromSeat: w['fromSeat'] as int,
              toSeat: w['toSeat'] as int,
            ),
        ],
      );

  List<Player> roster(Set<int> alive) => [
        for (var seat = 0; seat < 7; seat++)
          Player(
            seat: seat,
            name: 'P$seat',
            role: Role.citizen,
            status:
                alive.contains(seat) ? PlayerStatus.alive : PlayerStatus.dead,
            eliminatedOn: alive.contains(seat)
                ? null
                : const PhaseRef(phase: GamePhase.night, number: 1),
          ),
      ];

  test('the vector file is not empty and both sections are populated', () {
    expect(vectors['version'], equals(1));
    expect(vectors['traces'], isA<List>());
    expect((vectors['traces'] as List).length, greaterThan(10));
    expect((vectors['confrontations'] as List).length, greaterThan(10));
  });

  test('every trace type appears somewhere in the vectors', () {
    final produced = {
      for (final c in (vectors['traces'] as List))
        ((c as Map)['expected'] as Map)['type'] as String,
    };
    // Doc 11 §10: "every eligibility branch covered". A vector file that never
    // produces `t5` is a vector file that would not notice `t5` breaking.
    for (final type in TraceType.values) {
      expect(produced, contains(type.name),
          reason: '${type.name} is never exercised by the vectors');
    }
  });

  group('traces', () {
    test('the Dart generator reproduces every stored trace', () {
      for (final raw in (vectors['traces'] as List)) {
        final c = raw as Map<String, dynamic>;
        final result = selectTrace(
          night: decodeNight(c['night'] as Map<String, dynamic>),
          history: [
            for (final n in (c['history'] as List))
              decodeNight(n as Map<String, dynamic>),
          ],
          players: roster({for (final s in (c['alive'] as List)) s as int}),
          nightNumber: c['nightNumber'] as int,
          matchSeed: c['matchSeed'] as int,
        );
        final expected = c['expected'] as Map<String, dynamic>;
        expect(result.type.name, equals(expected['type']),
            reason: 'trace case "${c['name']}"');
        expect(result.subjectSeat, equals(expected['subjectSeat']),
            reason: 'trace case "${c['name']}"');
        expect(result.targetSeat, equals(expected['targetSeat']),
            reason: 'trace case "${c['name']}"');
        expect(result.count, equals(expected['count']),
            reason: 'trace case "${c['name']}"');
      }
    });
  });

  group('confrontations', () {
    test('the Dart generator reproduces every stored confrontation', () {
      for (final raw in (vectors['confrontations'] as List)) {
        final c = raw as Map<String, dynamic>;
        final alive = {for (final s in (c['alive'] as List)) s as int};
        final settings = c['settings'] as Map<String, dynamic>;
        final result = selectConfrontation(
          history: GameHistory(
            nights: [
              for (final n in (c['nights'] as List))
                decodeNight(n as Map<String, dynamic>),
            ],
            days: [
              for (final d in (c['days'] as List))
                decodeDay(d as Map<String, dynamic>),
            ],
            names: {for (final s in alive) s: 'P$s'},
            alive: alive,
          ),
          players: roster(alive),
          dayNumber: c['dayNumber'] as int,
          matchSeed: c['matchSeed'] as int,
          settings: MatchSettings(
            whisperEnabled: settings['whisperEnabled'] as bool,
            survivorConfrontationEnabled:
                settings['survivorConfrontationEnabled'] as bool,
          ),
        );
        final expected = c['expected'] as Map<String, dynamic>?;
        if (expected == null) {
          expect(result, isNull, reason: 'confrontation case "${c['name']}"');
          continue;
        }
        expect(result, isNotNull, reason: 'confrontation case "${c['name']}"');
        expect(result!.type.name, equals(expected['type']),
            reason: 'confrontation case "${c['name']}"');
        expect(result.targetSeat, equals(expected['targetSeat']),
            reason: 'confrontation case "${c['name']}"');
        expect(result.evidenceSeat, equals(expected['evidenceSeat']),
            reason: 'confrontation case "${c['name']}"');
        expect(result.evidenceSeat2, equals(expected['evidenceSeat2']),
            reason: 'confrontation case "${c['name']}"');
        expect(result.evidenceDay, equals(expected['evidenceDay']),
            reason: 'confrontation case "${c['name']}"');
        expect(result.count, equals(expected['count']),
            reason: 'confrontation case "${c['name']}"');
      }
    });

    test('no held-back type appears in any vector', () {
      // The vectors are also the record of *what the server is allowed to
      // publish*. A `c3`, `c9` or `c10` in this file would mean the port had
      // been handed a type that names a living player's night suspicion.
      for (final raw in (vectors['confrontations'] as List)) {
        final expected = (raw as Map)['expected'] as Map?;
        if (expected == null) continue;
        expect(const ['c2', 'c3', 'c9', 'c10'],
            isNot(contains(expected['type'])),
            reason: 'case "${raw['name']}" published ${expected['type']}');
      }
    });
  });
}
